ajax/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView
from views import PersonalTicketsView

urlpatterns = [
    url(r'^personal/', PersonalTicketsView.as_view()),
]



#http://djbook.ru/rel1.8/topics/auth/default.html

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from SpeakUpIn import urls as speakurls
from ajax import urls as ajaxurls
from info.views import MainView
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', MainView.as_view()),
    url(r'^login/', 'info.views.login', name='login'),
    url(r'^logout/', 'info.views.logout', name='logout'),
    url(r'^speakupinbound/', include(speakurls)),
    url(r'^ajax/', include(ajaxurls)),

]

admin.site.site_header = 'JV Call Center'

SpeakUpIn/forms.py
#*-* coding: utf-8 *-*
from django import forms

class NewTicketForm(forms.Form):

    SCHOOLS = (
       ("1",("КИЕВ Метро Житомирская - проспект Победы, 136, 3-й этаж.ТЦ VMB.")),
       ("2",("КИЕВ Метро Контрактовая площадь - ул. Спасская, 5, 2-й этаж")),
       ("3",("КИЕВ Метро Печерская - бул. Леси Украинки 26, 9 этаж.")),
        ("4",("КИЕВ Метро Позняки ул. А.Мишуги, 8 2 эт.")),
        ("5",("КИЕВ Метро Голосеевская – ул. Васильковская, 14. БЦ Стенд, 1 этаж.")),
        ("6",("КИЕВ Соломенская площадь -  БЦ Нест, ул. Урицкого, 45, 1-й этаж")),
        ("7",("КИЕВ Метро Минская  - Dreamtown,  Оболонский проспект, 1-Б")),
        (u"8",("ОДЕССА ул. Ришельевская 14, 5-й этаж")),
        ("9",("КИЕВ Метро Троещина - ул. Маяковского, 68, 2 этаж")),
        ("10",("КИЕВ Метро Университет - ул. Михаила Коцюбинского 14")),

   )

    phone = forms.CharField(max_length=50, label="Телефон", required=True)
    first_name = forms.CharField(max_length=50, label="Имя", required=True)
    last_name = forms.CharField(max_length=50, label="Фамилия", required=False)
    middle_name = forms.CharField(max_length=50, label="Отчество", required=False)
    city = forms.CharField(max_length=10, label="Город", required=True)
    age = forms.CharField(max_length=50, label="Возраст", required=True)
    school = forms.CharField(max_length=200, label="Школа", required=True)

templates/speakup/index.html
{% extends 'layouts/ticketsBase.html' %}
{% block content %}
    <img width="30%" height="12%" src="https://cherylmckay.files.wordpress.com/2012/09/speak-up-logo.png">
    <div class ="formHead"><b>Заявка на консультацию</b></div>
        <div id="formTicketContainer" class ="formContainer">



            <form method="POST" action="/speakupinbound/">
                {% csrf_token %}
            <div><p>
                {{ form.phone }} {{ form.phone.label }}<span style="color:red;">*</span><p>
                <p class="formError">{{ form.phone.errors }}</p>
             {{ form.first_name }} {{ form.first_name.label }}<span style="color:red;">*</span><p>
                <p class="formError">{{ form.first_name.errors }}</p>
             {{ form.last_name }} {{ form.last_name.label }}<p>
             {{ form.middle_name }} {{ form.middle_name.label }}<p>
             {{ form.city }} {{ form.city.label }}<span style="color:red;">*</span><p>
                <p class="formError">{{ form.city.errors }}</p>
             {{ form.age }} {{ form.age.label }}<span style="color:red;">*</span><p>
                <p class="formError">{{ form.age.errors }}</p>
             {{ form.school.label }}
                <p>
                <input id="id_school" name="school" class="awesomplete" list="selectSchool" />
                    <datalist id="selectSchool">
	                <option>г.Киев Метро Житомирская - проспект Победы, 136, 3-й этаж.ТЦ VMB.</option>
	                    <option>г.Киев Метро Контрактовая площадь - ул. Спасская, 5, 2-й этаж</option>
	                        <option>г.Киев Метро Печерская - бул. Леси Украинки 26, 9 этаж.</option>
	                            <option>г.Киев Метро Позняки ул. А.Мишуги, 8 2 эт.</option>
	                                <option>г.Киев Метро Голосеевская – ул. Васильковская, 14. БЦ Стенд, 1 этаж.</option>
	                                  <option>г.Киев Соломенская площадь -  БЦ Нест, ул. Урицкого, 45, 1-й этаж</option>
	                                        <option>г.Киев Метро Минская  - Dreamtown,  Оболонский проспект, 1-Б</option>
                                            <option>г. Одесса ул. Ришельевская 14, 5-й этаж</option>
                                            <option>г.Киев Метро Троещина - ул. Маяковского, 68, 2 этаж</option>
                                            <option>г.Киев Метро Университет - ул. Михаила Коцюбинского 14</option>



                                          </datalist>
                <input type="submit" value="Регистрация">

                </div>
            </form>

        </div>
</div>

<script>

</script>

{% endblock %}

templates/speakup/myTickets.html
{% extends 'layouts/ticketsBase.html' %}

{% block content %}
<form id="searchForm" name="searchForm">
    Телефон<input id="phone" type="text"><Br>
    Город<input id="formCity" type="text"><Br>
    Начало<input id="StartDatePicker" type="date" value="2016-01-01">
    Конец<input id="EndDatePicker" type="date">
    <button id="searchButton" type='button'>Найти</button>
</form>
        <script>
        var  currentDate = new Date()
        var tommorow = currentDate.setDate(currentDate.getDate() + 1);
        document.getElementById('EndDatePicker').valueAsDate = tommorow;

            $('#searchButton').click(function(){

            creationDateStart = $('#StartDatePicker').val();
            creationDateEnd = $('#EndDatePicker').val();
            var searchStr = '?creation_date__gte=' + creationDateStart + '&creation_date__lt=' + creationDateEnd;
            formCity = $('#formCity').val();
            formPhone = $('#phone').val();


            if(formPhone != '') {
                searchStr = searchStr+'&phone='+formPhone
            }

            if(formCity != '') {
                searchStr = searchStr+'&city='+formCity
            }
             window.location.href = "/speakupinbound/find/" + searchStr ;


            });

        </script>

    <script>

        $.getJSON( "/ajax/personal/", function( data ) {
  var items = [];
  $.each( data, function( key, val ) {
    console.log(key, val)
  }
        )
        }
  );

    </script>

    Всего записей: <b>{{ ticket_list.count }}</b> <a id="ss" href="#">Обновить<i id="refreshAjaxTable" class="fa fa-refresh"></i></a>
<table id="example" border="1" cellpadding="5" cellspacing="5" width="100%">
    <thead>
  <tr>
    <td class="tableHead">Номер</td>
    <td class="tableHead">ФИО</td>
    <td class="tableHead">Телефон</td>
    <td class="tableHead">Город</td>
    <td class="tableHead">Возраст</td>
    <td class="tableHead">Школа</td>
    <td class="tableHead">Дата создания</td>
  </tr>
        </thead>

        {% for ticket in ticket_list %}
  <tr id="tickets">

    <td>{{ ticket.id }}</td>
    <td>{{ ticket.first_name }} {{ ticket.last_name }} {{ ticket.middle_name }}</td>
    <td>{{ ticket.phone }}</td>
    <td>{{ ticket.city }}</td>
    <td>{{ ticket.age }}</td>
    <td>{{ ticket.place }}</td>
    <td>{{ ticket.creation_date }}</td>
  </tr>

        {% endfor %}
</table>

{% endblock %}
</html>

templates/speakup/recall.html
{% extends 'layouts/ticketsBase.html' %}
{% block content %}

    <!--<div class ="formHead"><b>Перезвон</b></div>
        <div class ="formContainer">
            <form>
            <p><span>Номер телефона </span> <input type="text">
            <p><span>Имя </span> <input type="text">
            <p><span>Фамилия </span> <input type="text">
            <p><span>Отчество </span> <input type="text">
            <p><span>Город </span> <input type="text">
            <p><span>Дата</span> <input type="datetime-local">
           <p><input type="submit" value="Регистрация">
            </form>

        </div>-->

       SSSSS

{% endblock %}
</html>